# Generated by Django 2.1.1 on 2018-09-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='free_count',
            field=models.IntegerField(default=10, help_text='免费使用额度'),
        ),
    ]
