# Generated by Django 2.1.1 on 2018-09-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20180928_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageuser',
            name='wechat_id',
            field=models.CharField(default='zhao546109656', help_text='管理员微信号', max_length=50),
        ),
        migrations.AlterField(
            model_name='manageuser',
            name='name',
            field=models.CharField(help_text='管理员名称', max_length=50),
        ),
        migrations.AlterField(
            model_name='manageuser',
            name='qrcode',
            field=models.ImageField(help_text='管理员二维码', upload_to='user_qrcode'),
        ),
        migrations.AlterField(
            model_name='user',
            name='free_count',
            field=models.IntegerField(default=3, help_text='免费使用额度'),
        ),
    ]
